micronaut:
  application:
    name: firstproject
    server:
      cors:
        enabled: true
      port: 8080
cassandra:
  default:
    basic:
      contact-points: http://localhost:9042/
      session-keyspace: tv-shows
      load-balancing-policy:
        local-datacenter: datacenter1
endpoints:
  health:
    enabled: true
